### ISSUE TITLE
Build fails on "npm install gzbz2": Missing node_events.h

### ISSUE THREAD

**Issue by mintplant** [Woodya/node-gzbz2#11]
> gzbz2@0.1.4 preinstall /home/[...]/node_modules/gzbz2
    > node-waf clean || true; node-waf configure build
    Nothing to clean (project not configured)
    Checking for program g++ or c++          : /usr/bin/g++ 
    Checking for program cpp                 : /usr/bin/cpp 
    Checking for program ar                  : /usr/bin/ar 
    Checking for program ranlib              : /usr/bin/ranlib 
    Checking for g++                         : ok  
    Checking for program gcc or cc           : /usr/bin/gcc 
    Checking for program ar                  : /usr/bin/ar 
    Checking for program ranlib              : /usr/bin/ranlib 
    Checking for gcc                         : ok  
    Checking for node path                   : not found 
    Checking for node prefix                 : ok /usr 
    Checking for library z                   : yes 
    Checking for library bz2                 : not found 
    'configure' finished successfully (3.188s)
    Waf: Entering directory `/home/[...]/node_modules/gzbz2/build'
    [1/2] cxx: compress.cc -> build/Release/compress_1.o
    ../compress.cc:2:25: fatal error: node_events.h: No such file or directory
    compilation terminated.
    Waf: Leaving directory `/home/krizz/dev/js/node/minecraft_js/node_modules/gzbz2/build'
    Build failed:  -> task failed (err #1): 
    	{task: cxx compress.cc -> compress_1.o}
    npm ERR! error installing gzbz2@0.1.4 Error: gzbz2@0.1.4 preinstall: `node-waf clean || true; node-waf configure build`
    npm ERR! error installing gzbz2@0.1.4 `sh "-c" "node-waf clean || true; node-waf configure build"` failed with 1
    npm ERR! error installing gzbz2@0.1.4     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/exec.js:49:20)
    npm ERR! error installing gzbz2@0.1.4     at ChildProcess.emit (events.js:70:17)
    npm ERR! error installing gzbz2@0.1.4     at maybeExit (child_process.js:359:16)
    npm ERR! error installing gzbz2@0.1.4     at Process.onexit (child_process.js:395:5)
    npm ERR! gzbz2@0.1.4 preinstall: `node-waf clean || true; node-waf configure build`
    npm ERR! `sh "-c" "node-waf clean || true; node-waf configure build"` failed with 1
    npm ERR! 
    npm ERR! Failed at the gzbz2@0.1.4 preinstall script.
    npm ERR! This is most likely a problem with the gzbz2 package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-waf clean || true; node-waf configure build
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls gzbz2
    npm ERR! There is likely additional logging output above.
    npm ERR! 
    npm ERR! System Linux 3.0.0-12-generic
    npm ERR! command "node" "/usr/bin/npm" "install" "gzbz2"
    npm ERR! cwd /home/[...]
    npm ERR! node -v v0.6.2
    npm ERR! npm -v 1.0.104
    npm ERR! code ELIFECYCLE
    npm ERR! 
    npm ERR! Additional logging details can be found in:
    npm ERR!     /home/[...]/npm-debug.log
    npm not ok

**Comment by Woodya** [comment]
hopefully this has been closed by v 0.2.0
