### ISSUE TITLE
node 0.6.0 compatibility

### ISSUE THREAD

**Issue by tungj** [Woodya/node-gzbz2#8]
node_events.h and the EventEmitter has been removed in node 0.5 and 0.6, which causes the build to fail with
../compress.cc:3: fatal error: node_events.h: No such file or directory. 

Would it be possible to update the module to compile against 0.6, now a stable build has been released? 

Is there any reason the classes have to extend EventEmitter, since they don't seem to use the Emit method?I've tried to modify it to extend ObjectWrap instead and call setClassName directly, which compiles but gives 'Unable to load shared library' errors; it's probably some mistake I've made.

**Comment by Woodya** [comment]
i believe this is now fixed due to another commit from @ripcurld00d that removed EventEmitter but didn't add static persistent<functiontemplate>
